baseURL: /
languageCode: en-us
title: JPL Research Team
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
params:
  google_analytics_id: ''
  homepage_meta_tags:
    meta_description: JPL Research Team aims to provide a high level of granularity in Statistical Research.
    meta_og_description: JPL Research Team aims to provide a high level of granularity in Statistical Analysis.
    meta_og_image: https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png
    meta_og_title: JPL Research Team
    meta_og_type: website
    meta_og_url: https://hugo-hero.netlify.app
    meta_twitter_card: summary
    meta_twitter_creator: '@zerostaticio'
    meta_twitter_site: '@zerostaticio'
menu:
  main:
    - name: Activities
      url: /Activities/
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Upcoming Events
      url: /Upcoming Events/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
